[[language]]
name = "rust"

[language-server.rust-analyzer.config.cargo]
target = "wasm32-unknown-unknown"
extraEnv = { RUSTFLAGS = "-C target-feature=+simd128" }

[language-server.rust-analyzer.config.check]
command = "check"
